# Generated by Django 5.0.6 on 2024-06-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_of_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='good_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
