# Generated by Django 5.0.6 on 2024-09-08 13:42

import django.db.models.deletion
import goods_of_home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_of_home', '0002_goods_good_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=250)),
                ('good_description', models.TextField()),
                ('good_location', models.TextField(blank=True, null=True)),
                ('good_image', models.ImageField(upload_to=goods_of_home.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
    ]
