# Generated by Django 5.0.6 on 2024-09-08 14:45

import django.db.models.deletion
import goods_of_home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_of_home', '0003_good_delete_goods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(max_length=250)),
                ('collection_description', models.TextField()),
                ('collection_location', models.TextField(blank=True, null=True)),
                ('collection_image', models.ImageField(upload_to=goods_of_home.models.user_directory_path)),
                ('goods', models.ManyToManyField(related_name='collections', to='goods_of_home.good')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
