# Generated by Django 5.0.6 on 2024-09-15 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods_of_home', '0004_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='goods',
            new_name='collection_goods',
        ),
    ]
