# Generated by Django 5.0.6 on 2024-09-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods_of_home', '0005_rename_goods_collection_collection_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='good_collection',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
