# Generated by Django 5.1.3 on 2024-12-20 03:51

import django.db.models.deletion
import stationery_items.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stationery_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationery_item_name', models.CharField(max_length=250)),
                ('stationery_item_description', models.TextField()),
                ('stationery_item_quantity', models.IntegerField()),
                ('stationery_item_image', models.ImageField(upload_to=stationery_items.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
