# Generated by Django 5.1.3 on 2024-12-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationery_item',
            old_name='stationery_item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='stationery_item',
            old_name='stationery_item_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='stationery_item',
            old_name='stationery_item_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stationery_item',
            old_name='stationery_item_quantity',
            new_name='quantity',
        ),
    ]
